### PR TITLE
Add dist for react-vr sample

### PR DESCRIPTION
**Pull request by shaoboyan**
Dist folder for react-vr sample : 
1. add simple cursor
2. add oculus touch support

### CODE REVIEW

**Comment by shaoboyan** [comment]
@huningxin  PTAL

**Comment by huningxin** [comment]
Thanks! I will test and merge today.

**Comment by huningxin** [comment]
Found path issue of layout, video and video 360 samples. Please check them. Thanks!

**Comment by shaoboyan** [comment]
@huningxin updated pr ,pls double check path issue. thx!

**Comment by huningxin** [comment]
Thanks! It seems missing remote button support. Please have a check.

**Comment by shaoboyan** [comment]
Updated pr :
1. Add sound and video for toursample
2. Add missing remote button support(no test)
3. Change video/video260 demo from webm format to mp4 format;

@huningxin  Pls double check ! thx!

**Comment by huningxin** [comment]
Cool! verified! Thanks.

**Pull request merged**
